site_name: Playfield VM ドキュメント
repo_url: https://github.com/awemorris/PlayfieldVM
use_directory_urls: false

nav:
  - Home: index.md
  - クイックガイド: gettingstarted.md
  - スクリプト文法: syntax.md
  - PlayfieldVM Engine API: api.md
  - ビルド方法: build.md
  - 移植状況: porting.md
  - 設計: design.md

theme:
  name: material
  features:
    - navigation.expand
    - navigation.tabs
    - search.suggest
    - content.code.annotate
