name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up dependencies
        run: |
          git submodule update --init

          brew update
          brew install mingw-w64 bison flex mkdocs-material
          echo "/opt/homebrew/opt/bison/bin" >> $GITHUB_PATH
          echo "/opt/homebrew/opt/flex/bin" >> $GITHUB_PATH

      - name: Verify versions
        run: |
          which bison
          bison --version
          which flex
          flex --version

      - name: Make the target directory.
        run: |
          mkdir dist
          mkdir dist/misc
          mkdir dist/misc/windows
          mkdir dist/misc/macos
          mkdir dist/misc/wasm
          mkdir dist/misc/ios
          mkdir dist/misc/android
          mkdir dist/misc/unity

      - name: Build for Windows.
        run: |
          cmake --preset windows-x86_64
          cmake --build --preset windows-x86_64
          x86_64-w64-mingw32-strip build-win-x86_64/picopico.exe
          x86_64-w64-mingw32-strip build-win-x86_64/picopico-pack.exe
          x86_64-w64-mingw32-strip build-win-x86_64/picopico-web.exe
          cp build-win-x86_64/picopico.exe dist/
          cp build-win-x86_64/picopico-pack.exe dist/misc/windows/
          cp build-win-x86_64/picopico-web.exe dist/misc/wasm/
          cp samples/bouncer/main.noct dist/

      - name: Setup for macOS
        uses: apple-actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.CERTIFICATE_FILE_BASE64 }}
          p12-password: ${{ secrets.CERTIFICATE_PASSWORD }}

      - name: Build for macOS
        shell: bash
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
          APP_SECRET: ${{ secrets.APP_PASSWORD }}
        run: |
          echo "AAAAAAAAAAAA"
          cmake --preset macos
          echo "BBBBBBBBBBBB"
          cmake --build --preset macos
          cd build-macos
          codesign --timestamp --options runtime --entitlements ../resources/macos/macos.entitlements --deep --force --sign "Developer ID Application" PicoPico.app
          ditto -c -k --sequesterRsrc --keepParent PicoPico.app PicoPico.zip
          xcrun notarytool submit PicoPico.zip --apple-id "$APPLE_ID" --team-id "$TEAM_ID" --password "$APP_SECRET" --wait
          xcrun stapler staple PicoPico.app
          mkdir tmp
          cp -Rv PicoPico.app tmp/PicoPico.app
          hdiutil create -fs HFS+ -format UDBZ -srcfolder tmp -volname PicoPico PicoPico.dmg
          codesign --sign "Developer ID Application" PicoPico.dmg
          cd ..
          cp build-macos/PicoPico.dmg dist/misc/macos/
          cp build-macos/picopico-pack dist/misc/macos/

      - name: Setup for Wasm
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest

      - name: Build for Wasm
        run: |
          cmake --preset wasm
          cmake --build --preset wasm
          cp build-wasm/index.html dist/misc/wasm/
          cp resources/assets.pak dist/misc/wasm/
          cp docs/readme/wasm.md dist/misc/wasm/readme.txt

      - name: Build for iOS
        run: |
          cmake --preset ios-device
          cmake --build --preset ios-device
          cmake --preset ios-simulator
          cmake --build --preset ios-simulator
          xcodebuild -create-xcframework -library build-ios-device/libpicopico.a -headers include -library build-ios-simulator/libpicopico.a -headers include -output PicoPico.xcframework
          mkdir dist/misc/ios/ios.xcodeproj
          cp resources/projects/ios/ios.xcodeproj/project.pbxproj dist/misc/ios/ios.xcodeproj/
          mkdir dist/misc/ios/ios
          cp -R resources/projects/ios/ios/Assets.xcassets dist/misc/ios/ios/
          cp resources/projects/ios/ios/entry.c dist/misc/ios/ios/
          cp resources/projects/ios/ios/Info.plist dist/misc/ios/ios/
          cp resources/projects/ios/ios/ios.entitlements dist/misc/ios/ios/
          cp resources/projects/ios/ios/LaunchScreen.storyboard dist/misc/ios/ios/
          cp -R PicoPico.xcframework dist/misc/ios/ios/
          mkdir dist/misc/ios/Resources/
          cp resources/assets.pak dist/misc/ios/Resources/
          mkdir dist/misc/ios/Resources/video

      - name: Setup for Android
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r28c

      - name: Build for Android
        run: |
          cmake --preset android-arm64
          cmake --build --preset android-arm64
          cmake --preset android-armv7
          cmake --build --preset android-armv7
          cmake --preset android-x86_64
          cmake --build --preset android-x86_64
          cmake --preset android-x86
          cmake --build --preset android-x86
          cp -R resources/projects/android/app dist/misc/android/
          cp -R resources/projects/android/gradle.properties dist/misc/android/
          cp -R resources/projects/android/build.gradle dist/misc/android/
          cp -R resources/projects/android/gradlew dist/misc/android/
          cp -R resources/projects/android/settings.gradle dist/misc/android/
          cp -R resources/projects/android/gradlew.bat dist/misc/android/
          cp -R resources/projects/android/gradle dist/misc/android/
          cp -R resources/projects/android/build.bat dist/misc/android/
          mkdir -p dist/misc/android/app/src/main/assets
          cp samples/bouncer/main.noct dist/misc/android/app/src/main/assets/
          mkdir -p dist/misc/android/app/src/main/java/io/noctvm/picopico/engineandroid
          cp external/StratoHAL/src/MainActivity.java dist/misc/android/app/src/main/java/io/noctvm/picopico/engineandroid/
          mkdir -p dist/misc/android/app/src/main/jniLibs/arm64-v8a
          cp build-android-arm64/libpicopico.so dist/misc/android/app/src/main/jniLibs/arm64-v8a/
          mkdir -p dist/misc/android/app/src/main/jniLibs/armeabi-v7a
          cp build-android-armv7/libpicopico.so dist/misc/android/app/src/main/jniLibs/armeabi-v7a/
          mkdir -p dist/misc/android/app/src/main/jniLibs/x86_64
          cp build-android-x86_64/libpicopico.so dist/misc/android/app/src/main/jniLibs/x86_64/
          mkdir -p dist/misc/android/app/src/main/jniLibs/x86
          cp build-android-x86/libpicopico.so dist/misc/android/app/src/main/jniLibs/x86/

      - name: Setup for Unity
        run: |
          curl -L -o llvm.tar.xz https://github.com/llvm/llvm-project/releases/download/llvmorg-20.1.8/LLVM-20.1.8-macOS-ARM64.tar.xz
          mkdir llvm-20 && tar -xJf llvm.tar.xz -C llvm-20 --strip-components=1
          echo "`pwd`/llvm-20/bin" >> $GITHUB_PATH
          #echo "DYLD_LIBRARY_PATH=`pwd`/llvm-20/lib" >> $GITHUB_ENV
          clang --version

      - name: Build for Unity
        run: |
          cmake --preset unity-win64
          cmake --build --preset unity-win64
          cmake --preset unity-switch
          cmake --build --preset unity-switch
          cmake --preset unity-ps5
          cmake --build --preset unity-ps5
          cmake --preset unity-xbox
          cmake --build --preset unity-xbox
          mkdir dist/misc/unity/Assets
          mkdir dist/misc/unity/Assets/StreamingAssets
          cp samples/bouncer/main.noct dist/misc/unity/Assets/StreamingAssets/
          mkdir dist/misc/unity/Assets/Resources
          cp external/StratoHAL/src/PicoPicoScript.cs dist/misc/unity/Assets/
          cp external/StratoHAL/src/NormalShader.shader dist/misc/unity/Assets/Resources/
          cp external/StratoHAL/src/AddShader.shader dist/misc/unity/Assets/Resources/
          cp external/StratoHAL/src/DimShader.shader dist/misc/unity/Assets/Resources/
          cp external/StratoHAL/src/RuleShader.shader dist/misc/unity/Assets/Resources/
          cp external/StratoHAL/src/MeltShader.shader dist/misc/unity/Assets/Resources/
          cp external/StratoHAL/src/MainScene.unity dist/misc/unity/Assets/
          mkdir dist/misc/unity/Assets/Plugins
          mkdir dist/misc/unity/Assets/Plugins/x86_64
          mkdir dist/misc/unity/Assets/Plugins/Switch
          mkdir dist/misc/unity/Assets/Plugins/PS5
          mkdir dist/misc/unity/Assets/Plugins/GameCoreXboxSeries
          mkdir dist/misc/unity/Assets/Plugins/Common
          cp build-unity-win64/libpicopico.dll dist/misc/unity/Assets/Plugins/x86_64/
          cp build-unity-switch/libpicopico.a dist/misc/unity/Assets/Plugins/Switch/
          cp build-unity-ps5/libpicopico.a dist/misc/unity/Assets/Plugins/PS5/
          cp build-unity-xbox/picopico.lib dist/misc/unity/Assets/Plugins/GameCoreXboxSeries/
          cp docs/readme/unity.md dist/misc/unity/

      - name: Make documents
        run: |
          cd docs/mkdocs-en
          mkdocs build
          mv site ../../dist/documents-english
          cd ../..
          cd docs/mkdocs-ja
          mkdocs build
          mv site ../../dist/documents-japanese
          cd ../..
          cp -R samples dist/samples
          cp resources/readme.txt dist/
          cp resources/hajimeni.txt dist/

      - name: Make documents
        run: |
          cd dist
          zip -r -9 PicoPicoScript.zip *
          cd ..

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PicoPicoScript.zip
          path: dist/PicoPicoScript.zip

      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly-${{ env.DATE }}-${{ github.sha }}
          name: Nightly Build ${{ env.DATE }}-${{ github.sha }}
          files: dist/PicoPicoScript.zip
          body: |
            This is an automated nightly build.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
